name: EthicalCheck-Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '18 9 * * 4'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  api-security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run API Security Scan
        uses: 42Crunch/api-security-audit-action@v1
        with:
          api-token: ${{ secrets.API_42CRUNCH_TOKEN }}
          sarif-report: api-audit.sarif
        continue-on-error: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: api-audit.sarif
